# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.6.0-4-g80716cc
_src_path: .
for_seedcase: true
github_repo: t-squared
github_user: seedcase-project
hosting_provider: netlify
