# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.7.4
_src_path: gh:seedcase-project/t-squared
for_seedcase: true
github_repo: t-squared
github_user: seedcase-project
hosting_provider: netlify
