project:
  # TODO: Update if using an extension.
  type: website
  render:
    # Don't render anything in the template directory.
    - "!template/"
    - "*.qmd"
    - "*.md"

website:
  # TODO: Set the title of the website
  title: ""
  # TODO: Set the Netlify custom domain URL
  site-url: ""
  repo-url: "https://github.com/seedcase-project/t-squared"
  favicon: "_extensions/seedcase-project/seedcase-theme/logos/seedcase/icon.svg"
  navbar:
    logo: "_extensions/seedcase-project/seedcase-theme/logos/seedcase/icon.svg"
    logo-alt: "Seedcase Project logo: Main page"
    pinned: true
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Guide"
        href: docs/guide.qmd
    tools:
      - icon: github
        href: "https://github.com/seedcase-project/t-squared"
        aria-label: "GitHub icon: Source repository"
      - icon: house
        href: "https://seedcase-project.org"
        aria-label: "House icon: Main website for the Seedcase Project"
  sidebar:
    - id: overview
      pinned: true
      style: "floating"
      contents:
        - text: "Welcome"
          href: index.qmd
        - CHANGELOG.md
        - CONTRIBUTING.md

format:
  seedcase-theme-html
    # TODO: Uncomment if using the goatcounter website visitor counter
    # include-before-body:
      # - "includes/site-counter.html"
