---
title: "Using the template"
description: |
  A walk-through on how to use this template for creating a new template project or
  applying it to an existing template project.
order: 2
---

This guide walks through how to use this template to create a new template
project or apply it to an existing template project.

## Creating a new template project

You can use this template to create a new template project with a standard set
of files and folders, as well as all the features and configurations to make it
easier to build your template project smoothly and effectively. First, open a
terminal and change your working directory to a location you want to create the
new template project in, e.g. `Documents/`:

```bash {filename="Terminal"}
cd Documents
```

Next, copy and paste the following command, replacing the `NAME` with the name
you want for your new template project. The `NAME` is the name you want to give
for the new template project's directory and (ideally) the GitHub repository for
the template project. The name should be something short and meaningful, ideally
lowercase, with `-` instead of spaces, and no special characters.

```bash {filename="Terminal"}
uvx copier copy gh:seedcase-project/t-squared NAME
```

The `copy` command uses the template on GitHub (`gh:`) at the
`seedcase-project/t-squared` location.

## Applying to an existing template project

If you want to use this template on an existing template project, you can use
the `copy` command of `copier` just like above to apply the template to the
existing template project. This will add all the template's files and
configurations to the existing template project. First, open a terminal and move
your working directory to the existing template project's directory:

```bash {filename="Terminal"}
cd Documents/EXISTING-PROJECT
```

Next, copy and paste the command below. The `.` means "use the template in the
current directory":

```bash {filename="Terminal"}
uvx copier copy gh:seedcase-project/t-squared .
```

See the comment above in the "Creating a new template project" section about the
naming of the existing template project directory. It will go through a series
of prompts, as in the case of creating a new template project, including asking
if you want to overwrite existing files.

::: callout-note
To use the `copy` command, the existing template project needs to be tracked by
Git and in a clean state (no changes have been made in the working directory).
:::
