name: Test template

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    # Least privilege permissions
    permissions: read-all
    steps:
      # This is a useful security step to check for unexpected outbound calls from the runner,
      # which could indicate a compromised token or runner.
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Set up uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867
        with:
          enable-cache: true

      - name: Install justfile
        run: uv tool install rust-just

      - name: Set Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "fake@example.com"

      # TODO: Confirm name of recipe to test template creation.
      - name: Test and check template creation
        run: just test-all
