name: Test template

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # This is a useful security step to check for unexpected outbound calls from the runner,
      # which could indicate a compromised token or runner.
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true

      - name: Install justfile
        run: uv tool install rust-just

      - name: Set Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "fake@example.com"

      # TODO: Confirm name of recipe to test template creation.
      - name: Test and check template creation
        run: just test-all
